apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  serviceAccount: jenkins
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug-v0.18.0
      command:
        - /busybox/cat
      tty: true
    - name: maven
      image: maven:3.8.2-jdk-11
      command:
        - cat
      tty: true